---
- name: files
  file:
    path: "{{item.path}}"
    state: "{{item.state|default(omit)}}"
    src: "{{item.src|default(omit)}}"
    force: "{{item.force|default(omit)}}"
    mode: "{{item.mode|default(omit)}}"
    owner: "{{item.owner|default(omit)}}"
    group: "{{item.group|default(omit)}}"
    recurse: "{{item.recurse|default(omit)}}"
  with_items: "{{cops_zope_vars.files}}"
  tags: [cops_zope_s_layout_layout]
  when: [cops_zope_s_layout_layout]
