---
- include_tasks: "{{cops_playbooks}}/provision/{{cops_installer_mode}}/tasks/load_vars.yml"
- {include_tasks: tasks/app_steps.yml}
- {include_role: {name: zope_vars, allow_duplicates: false}, become: true}
